name: "Get PR Number"
description: "Get The PR Number Based On Branch Name"
author: "Omoruyi Omofonmwan"

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  repository:
    description: "GitHub Repo"
    required: true
  branch_name:
    description: "GitHub Branch Name"
    required: true
  
outputs:
  pr_url:
    description: "Pull Request URL"
  pr_exists:
    description: "Checks whether PR exists"
  pr_number:
    description: "Pull Requests Number"
  pr_html_url:
    description: "Pull Request HTML URL"

runs:
  using: 'node20'
  main: index.js
